services:
    nginx:
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ../src:/srv/www
        build: nginx
    php-fpm:
        container_name: php-fpm
        build: php
        volumes_from:
            - nginx
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend

volumes:
    mysql_data:

networks:
    backend:
        driver: bridge